### PR TITLE
implements Interval coercion

### PR DESCRIPTION
**Pull request by gsmet**
Interval coercion is missing and it's an issue for one of our applications.

I implemented it as everything was already ready for that and added a test case.

### CODE REVIEW

**Comment by brettwooldridge** [comment]
@gsmet This looks good, can you add a test for coercion failure?  And if possible, add a test for _interval_ to _string_ conversion?

**Comment by gsmet** [comment]
Hi Brett,

Any pointers on similar tests for the other coercions? IIRC, I tried to be consistent with the tests existing for the other coercions but I might have missed something and, if so, I would prefer to take a look at what's existing to be as much as similar as possible.

Thanks.

**Comment by brettwooldridge** [comment]
To be honest, I haven't looked at the other (existing) coercion tests and it is possible that they are less than thorough.  I was just basing my recommendations on looking at the changes you made as well as the test to cover them.  It seemed that only the "positive" coercion case was tested, and only going from String→Interval.  I leave it to your discretion as to how deeply to test, but it seems that adding two simple tests, one coercion failure, and one Interval→string, would be enough.

**Comment by gsmet** [comment]
OK, I'll see what I can do.

I'm on the road this week so don't hold your breath but I'll take a shot at it next week so that we can get this committed soon.

**Comment by gsmet** [comment]
I had some spare time so I polished the tests a bit.

I'm not sure it's a good idea to depend on the implementation details of the Interval string representation.

Thoughts?

**Comment by brettwooldridge** [comment]
Is the string representation something that can change, i.e. configurable in PostgreSQL in some way?  Or is it entirely internal to the pgjdbc-ng driver?  If a change in the Interval string representation could break pgjdbc-ng's handling of the Interval, I think it is acceptable (and valid) to test based on the implementation details.

**Comment by gsmet** [comment]
> Is the string representation something that can change, i.e. configurable in PostgreSQL in some way?

The interval style is configurable in PostgreSQL: there are several variants.

See:
- http://www.postgresql.org/docs/9.1/static/runtime-config-client.html#GUC-INTERVALSTYLE
- http://www.postgresql.org/docs/9.1/static/datatype-datetime.html#DATATYPE-INTERVAL-INPUT

But in our case, it should be stable from the driver point of view as it treats the interval values in a non ambiguous way.

See especially this paragraph:

> According to the SQL standard all fields of an interval value must have the same sign, so a leading negative sign applies to all fields; for example the negative sign in the interval literal '-1 2:03:04' applies to both the days and hour/minute/second parts. PostgreSQL allows the fields to have different signs, and traditionally treats each field in the textual representation as independently signed, so that the hour/minute/second part is considered positive in this example. If IntervalStyle is set to sql_standard then a leading sign is considered to apply to all fields (but only if no additional signs appear). Otherwise the traditional PostgreSQL interpretation is used. To avoid ambiguity, it's recommended to attach an explicit sign to each field if any field is negative.

As for the other point:

>  If a change in the Interval string representation could break pgjdbc-ng's handling of the Interval, I think it is acceptable (and valid) to test based on the implementation details.

There are other tests below testing exactly that. It was more to make the test as "unit" as possible but I think it should be ok.

**Comment by brettwooldridge** [comment]
Excellent.

**Comment by brettwooldridge** [comment]
Looks good, thanks for the contribution!  Ready to merge?

**Comment by gsmet** [comment]
Let me squash it so that we got only one commit. I'll ping you when it's done!

**Comment by gsmet** [comment]
Done. You can merge it.

Thanks!

**Comment by gsmet** [comment]
Hmmm, got a checkstyle issue in the new code. Fixing it.

**Comment by gsmet** [comment]
OK, this time, it's ready to merge.

**Pull request merged**
