### PR TITLE
escape ? operator with ??

### PR DESCRIPTION
**Pull request by pkolaric**
escape ? jsonb operator (used in postgresql 9.4+ https://www.postgresql.org/docs/9.4/static/functions-json.html) with double ??

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Could you add a test case for this too ?

**Comment by pkolaric** [comment]
I've added the two additional operators that start with ? and a test case.

**Comment by jesperpedersen** [comment]
Your test case needs
```java
    if (!((PGConnection)con).isServerMinimumVersion(9, 4))
      return;
```
in order for the Travis build to pass. Also, you could squash your commits ?

**Comment by pkolaric** [comment]
Ah, completely missed that one... Thanx.

**Comment by jesperpedersen** [comment]
Merged, thanks for your contribution !

**Pull request merged**
