### PR TITLE
minimal support for external extensions to pgjdbc datatypes

### PR DESCRIPTION
**Pull request by frode-carlsen**
Since #178 is on hold, I'd like to make the following minor changes to the existing project to ease creating external datatype extensions to the library.

### CODE REVIEW

**Comment by kdubb** [comment]
Does this conform to our checkstyle?  I thought "protected" should be on the same line as the method definition.

**Comment by frode-carlsen** [comment]
interesting, it passed the checkstyle tests so looks like that's not enforced. 
I used automated refactoring to make the change, so I have no qualms about changing it to be on the same line.  Will check in

**Comment by jesperpedersen** [comment]
@frode-carlsen Could you fix the indentation of the pom.xml file change ? Then rebase, and squash. Thanks

**Comment by frode-carlsen** [comment]
ok, made some cosmetic changes to make it align same as plugins with above/below, but the whole pom.xml needs reformatting.  It's a mix of tabs and spaces and improperly aligned child elements.  Can do it here, but think perhaps it should be a different PR?

**Comment by jesperpedersen** [comment]
@frode-carlsen Just format to spaces here, but squash your commits too

**Comment by frode-carlsen** [comment]
how about this?

**Comment by jesperpedersen** [comment]
Rebased, and merged. Thanks for your contribution !

**Pull request closed without merging**
