### PR TITLE
Rebased version of the patches of Mikko Tiihonen

### PR DESCRIPTION
**Pull request by gsmet**
This pull request replaces https://github.com/impossibl/pgjdbc-ng/pull/73 .

I've merged Mikko's changes in the latest devel branch.

### CODE REVIEW

**Comment by kdubb** [comment]
This means I should close #73 correct?

**Comment by kdubb** [comment]
Do you guys things we should add a "tag" to the Version structure so that we can keep the "devel" & "beta" tags as well?

**Comment by gsmet** [comment]
Hi Kevin,

Yes, #73 is replaced by #91 + #84 (#84 is more complete and cleaner that what was proposed in the relevant part of #73: I updated all the dependencies and ignored the Guava classes in the checkstyle conf instead of reformatting them). We can close #73.

As for tagging the version, I don't see the point in it currently. The devel and beta versions of PostgreSQL are a transient process and they aren't supposed to be different from the app point of view. The only reason I can see is if someone is using the Version to display the PostgreSQL version of the server. We don't do it but it might be something someone could need.

If we do it, we could maybe name it qualifier as it's done in the Maven version convention (http://docs.codehaus.org/display/MAVEN/Versioning).

I can work on it if you think it's a good idea.

## 

Guillaume

**Comment by andreak** [comment]
Is this going to be merged any time soon?

**Pull request merged**
