### PR TITLE
Revamp how settings are defined, found & stored

### PR DESCRIPTION
**Pull request by kdubb**
Added a `Setting` object which defines information related to each setting (description, name, alternate names, default value, etc).  Settings can even define a dynamic source for it’s default value. This will ensure that we always know everything about each setting we define and where/how the default values are determined.  Removes a lot of parameter/setting copying code to make sure things are named right and in the right properties instance.

Also, added `Settings` which is much like `java.util.Properties` in that it stores everything in text but it allows access via `Setting` definitions.  `Settings` logs warnings for unrecognized names and logs errors for invalid values that are stored.

See `JDBCSettings` (previously `PGSettings`) & `SystemSettings` to see how the definitions have changed.

Allowing alternate names for a setting allows changing them in the future. This isn’t just a “nice to have” currently we use incorrect names for datasource properties; this allows a backwards compatible fix for issues like #315.

### CODE REVIEW

**Comment by kdubb** [comment]
@jesperpedersen In the recent commit I made a decision to require that all settings have a primary name in lowercase dot-dash format (e.g. `this.is.a.property-name`).  I generally prefer this format for settings because they seem easier to remember and type correctly without intermixed case.

The dotted format is easily convertible to a JavaBean property name (e.g.  it becomes `thisIsAPropertyName`), which I rely upon in the new `AbstractDataSource` implementation. It's also used in the new associated test that ensures all settings from the related setting groups are available on `AbstractDataSource` as bean properties.

I generally like this change, but it means going forward all properties must have a primary name matching this format.  Wanted to get outside input before deciding.

**Review by jesperpedersen — DISMISSED** [review]
I'm ok with these changes.

However, `README.md` needs to be updated to document the default properties

**Comment by kdubb** [comment]
I'm working on auto-generating a properties document from the settings and going to link to it from `README.md`

**Comment by jesperpedersen** [comment]
Ok, cool

**Pull request merged**
