### PR TITLE
Add OSGi headers to MANIFEST.MF

### PR DESCRIPTION
**Pull request by brettwooldridge**
Add OSGi headers to MANIFEST.MF so that the JAR can be used as an OSGi bundle in containers like Apache Felix and Eclipse Equinox.

### CODE REVIEW

**Comment by kdubb** [comment]
Is it possible to export only a single class in OSGi? I'm thinking it would be better to export PGDriver only.

Either way, the _com.impossibl.postgres.api.jdbc_ package needs to be exported as well.

**Comment by brettwooldridge** [comment]
In OSGi It is not possible to export a single class.  Basically, any package with classes that the user can directly reference (by class name) needs to be exported.  Will a user directly reference PGConnection in their code?  If so, I'll add _com.impossibl.postgres.api.jdbc_ package to the exports.

**Comment by kdubb** [comment]
Yes.  The c.i.p.jdbc.api package is for the public API of the driver specific extensions to the JDBC API.

**Comment by brettwooldridge** [comment]
Added.

**Pull request merged**
