### PR TITLE
Fix where localePart == "Chinese (Simplified)"

### PR DESCRIPTION
**Pull request by Hai-tun**

### CODE REVIEW

**Comment by kdubb** [comment]
What platform is this running on?

**Comment by Hai-tun** [comment]
`Operating System` : `Windows 10`
`PostgreSQL Version` :  `PostgreSQL 13.1, compiled by Visual C++ build 1914, 64-bit`
`Language` : `Chinese (Simplified)`
`Framework Used` : [JetBrains/Exposed](https://github.com/JetBrains/Exposed)
`Related Code` : 
```Kotlin
Database.connect(url = "jdbc:pgsql://localhost:5432/userservice", driver = "com.impossibl.postgres.jdbc.PGDriver", user = "postgres", password = "postgres")
transaction {
    addLogger(StdOutSqlLogger)
    SchemaUtils.create(Users)
}
```
`Related Errors` : 
```
Exception in thread "main" java.lang.IllegalArgumentException: Locale part "Chinese (Simplified)" contains invalid characters
	at com.impossibl.postgres.utils.Locales.validateLocalePart(Locales.java:152)
	at com.impossibl.postgres.utils.Locales.parseLocaleTokens(Locales.java:95)
	at com.impossibl.postgres.utils.Locales.parseLocale(Locales.java:70)
	at com.impossibl.postgres.system.BasicContext.loadServerLocales(BasicContext.java:394)
	at com.impossibl.postgres.system.BasicContext.init(BasicContext.java:382)
	at com.impossibl.postgres.jdbc.PGDirectConnection.init(PGDirectConnection.java:290)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:319)
	at com.impossibl.postgres.jdbc.ConnectionUtil.createConnection(ConnectionUtil.java:279)
	at com.impossibl.postgres.jdbc.PGDriver.connect(PGDriver.java:104)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:247)
	at org.jetbrains.exposed.sql.Database$Companion$connect$10.invoke(Database.kt:148)
	at org.jetbrains.exposed.sql.Database$Companion$connect$10.invoke(Database.kt:58)
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:112)
	at org.jetbrains.exposed.sql.Database$Companion$doConnect$3.invoke(Database.kt:58)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:54)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction$connectionLazy$1.invoke(ThreadLocalTransactionManager.kt:46)
	at kotlin.UnsafeLazyImpl.getValue(Lazy.kt:81)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManager$ThreadLocalTransaction.getConnection(ThreadLocalTransactionManager.kt:60)
	at org.jetbrains.exposed.sql.Transaction.getConnection(Transaction.kt)
	at org.jetbrains.exposed.sql.vendors.VendorDialect.tableExists(Default.kt:645)
	at org.jetbrains.exposed.sql.QueriesKt.exists(Queries.kt:191)
	at org.jetbrains.exposed.sql.SchemaUtils.createStatements(SchemaUtils.kt:78)
	at org.jetbrains.exposed.sql.SchemaUtils.create(SchemaUtils.kt:180)
	at org.jetbrains.exposed.sql.SchemaUtils.create$default(SchemaUtils.kt:178)
	at pl.edu.moe.userservice.MainKt$main$1.invoke(Main.kt:28)
	at pl.edu.moe.userservice.MainKt$main$1.invoke(Main.kt)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$1.invoke(ThreadLocalTransactionManager.kt:170)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$inTopLevelTransaction$2.invoke(ThreadLocalTransactionManager.kt:211)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.inTopLevelTransaction(ThreadLocalTransactionManager.kt:210)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt$transaction$1.invoke(ThreadLocalTransactionManager.kt:148)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.keepAndRestoreTransactionRefAfterRun(ThreadLocalTransactionManager.kt:219)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:120)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction(ThreadLocalTransactionManager.kt:118)
	at org.jetbrains.exposed.sql.transactions.ThreadLocalTransactionManagerKt.transaction$default(ThreadLocalTransactionManager.kt:117)
	at pl.edu.moe.userservice.MainKt.main(Main.kt:26)
	at pl.edu.moe.userservice.MainKt.main(Main.kt)
```

**Comment by kdubb** [comment]
@Hai-tun Is it possible to add test coverage for this?

**Comment by Hai-tun** [comment]
@kdubb Sorry, I don't think it is possible to add test coverage and I don't know how to.

**Pull request merged**
