### PR TITLE
Upgrade to netty 4.0.15.Final

### PR DESCRIPTION
**Pull request by normanmaurer**
Boom ! ;)

### CODE REVIEW

**Comment by jesperpedersen** [comment]
Looks good ! Thanks for your contribution :)

@kdubb Test suite is passing, and performance is increased. So ready for merge.

**Comment by normanmaurer** [comment]
Nice! What kind of improvement you see? Gimme some numbers ;)

**Comment by jesperpedersen** [comment]
@normanmaurer 5+% on a simple case, further tests are pending

**Comment by normanmaurer** [comment]
Nice… Keep me posted :)
-- 
Norman Maurer

An 18. Dezember 2013 at 11:08:06, Jesper Pedersen (notifications@github.com) schrieb:

@normanmaurer 5+% on a simple case, further tests are pending

**Comment by brettwooldridge** [comment]
Just a curious onlooker, wondering why this pull request from a month ago hasn't been pulled.  I know large changes are hard to review, but having just gone through a painful Netty3 → Netty4 migration the number of changes was both massive and unavoidable.

**Comment by kdubb** [comment]
Only because this was finished just before I went on vacation... and of course I had to catch up on work after the new year.  This will be integrated in the next couple of days.  My fail.

**Comment by normanmaurer** [comment]
Netty 4.0.15.Final was just released. Maybe you want upgrade to it directly?

**Comment by jesperpedersen** [comment]
@normanmaurer Yeah, do that, and squash. Otherwise I'll do a separate PR after the merge.

**Comment by normanmaurer** [comment]
@jesperpedersen done ... also rebased on latest develop branch

**Pull request merged**
