### PR TITLE
Cleanup JDBC/Type mapping

### PR DESCRIPTION
**Pull request by kdubb**
* Remove `PrimitiveType` completely, types are now directly mapped to JDBC type using `PGType`
* Replaces all use of `java.sql.Types` in the mapping process with `SQLType`
* Implements some missed JDBC 4.2 methods in `PGCallableStatement` that use `SQLType` mapping
* Uses `PGType` to produce data for `JDBCTypeMetaData`
* Moves all `Object` to `SQLType` discovery to `JDBCTypeMapping`

### CODE REVIEW

**Comment by kdubb** [comment]
It's a large charge only in that it touches a lot of files. Each Decoder was required to implement a method that provided its `PrimitiveType` but this enum was inaccurate and not needed after rework; so it was removed.

**Comment by jesperpedersen** [comment]
There is something wrong with skipping the SSL tests, if the server is started manually with no SSL support

**Comment by jesperpedersen** [comment]
Using the full setup (hstore, citext, sslinfo) with all the databases, and the tests passes.

LGTM

**Comment by jesperpedersen** [comment]
Something to note; PostgreSQL 12 will remove support for `WITH OIDS`

**Comment by kdubb** [comment]
`WITH OIDS` only affects non system tables correct? I'm assuming the system tables will all retain their `oid` column, or will it be renamed?

**Comment by jesperpedersen** [comment]
Just user tables; and a quick look at the 2 test cases doesn't really show anything that can't be removed

**Pull request merged**
