### PR TITLE
Checkstyle fixes

### PR DESCRIPTION
**Pull request by moio**
Just two small fixes as gradle complained today

### CODE REVIEW

**Comment by moio** [comment]
(seems like Travis failures are unrelated)

**Comment by kdubb** [comment]
@moio The failure was a Travis service hiccup. I added `checkstyleTest` to the `checks` stage ensure that Travis checks all source now.

**Review by kdubb — COMMENTED** [review]
👍

**Review by kdubb — APPROVED** [review]
👍

**Pull request merged**
