### PR TITLE
Add "alter table while holding a server-prepared statement" test

### PR DESCRIPTION
**Pull request by vlsi**
See https://github.com/pgjdbc/pgjdbc/pull/451.

This test fails with

```
com.impossibl.postgres.jdbc.PGSQLSimpleException: cached plan must not change result type

    at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:159)
    at com.impossibl.postgres.jdbc.ErrorUtils.makeSQLException(ErrorUtils.java:136)
    at com.impossibl.postgres.jdbc.PGConnectionImpl.execute(PGConnectionImpl.java:442)
    at com.impossibl.postgres.jdbc.PGStatement.executeStatement(PGStatement.java:375)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.execute(PGPreparedStatement.java:267)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:283)
    at com.impossibl.postgres.jdbc.PGPreparedStatement.executeQuery(PGPreparedStatement.java:93)
    at com.impossibl.postgres.jdbc.PreparedStatementTest.testChangeType(PreparedStatementTest.java:1282)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47)
    at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
    at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44)
    at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70)
    at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50)
    at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
    at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
    at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
    at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
    at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
    at org.junit.runner.JUnitCore.run(JUnitCore.java:160)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

### CODE REVIEW

**Comment by kdubb** [comment]
Clearly these will fail. Are you suggesting the right solution would be to retry as in the PR you mentioned?

I think I'm most inclined to say "don't do that".  I'm most accustomed to database schemas remaining relatively unchanged. In the cases where they are not I'm inclined to require them to not use prepared statements.

**Comment by kdubb** [comment]
The "DEALLOCATE ALL" call to me is the same answer.  You created a prepared statement then specifically deallocated it.  It would expect it to fail.

**Comment by vlsi** [comment]
Well, that is why I added "Lack of `prepared statement invalidated` messages from backend" entry to the "most wanted" list.

Frankly speaking, I'm not 100% sure it is safe. However, it's better to have a definitive answer than create "undefined behavior"

**Comment by kdubb** [comment]
Well for "DEALLOCATE ALL"  or "DEALLOCATE <blah>" you could read the command tag... and you'd know when somebody explicitly deallocated the prepared statement and prepare it again internally.

The first test you presented is the case where there is no good answer.

**Comment by kdubb** [comment]
Actually, on second thought, tracking the table name that the PreparedStatement is attached to... then watching for the "ALTER TABLE" command tag would allow you to prepare the statement internally as well.

**Comment by vlsi** [comment]
You would anyway miss "alters" that happen in pl/v8.

**Comment by vlsi** [comment]
@kdubb , what is the way to enable "trace logging" in pgjdbc-ng so I can see which messages go over the wire?

**Comment by kdubb** [comment]
Agreed, it wouldn't catch everything, but it would catch direct errors.  It would also prepare for the future if/when a notification of deallocation is added to the protocol.

**Comment by kdubb** [comment]
We have no such logging trace.  It's been on my list for a while but hasn't been added as of yet.  I might just do that next since I am working on the driver at the moment.

**Comment by vlsi** [comment]
> It would also prepare for the future if/when a notification of deallocation is added to the protocol.

If backend would ever learn to share prepared statements across connections, we might need to handle that as well. Not sure if we need to account that in v4 though.

**Comment by kdubb** [comment]
Add that to your backend wishlist!! (unless I just missed it).  Sharing prepared statements would be great.

**Comment by vlsi** [comment]
> I might just do that next since I am working on the driver at the moment.

It's not that important for me.
I was just curious why `test batch with alternating bind types` is not reproduced in -ng: https://github.com/pgjdbc/pgjdbc/pull/449/files#diff-efc8c3eee49c38f1557353bff58b7e94R436

It might be already fixed somehow, or it might be just "better hidden", thus I wanted to get message trace.

**Pull request closed without merging**
